# Generated by Django 4.2.4 on 2023-08-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Person_name',
        ),
    ]
