# Generated by Django 4.2.4 on 2023-08-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_alter_menu_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Menucategory',
        ),
    ]
